# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d3bd4e802f96db27953c9488e99751b65e1a2722c5483fdad94544de72af7e7b858d8ad60e92d1e5a7401ff67de380f16a13e4d8b342222762a1f99cb21cede

test:
  secret_key_base: 972c7fa40acdd728f87d5d9db71ca8ce3d3ab0deb07f76a07414c7db155f853ed4837ee04de13c8ede1a9fad6da9a2bcde8aced08589034edd829b7d82658bb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
